# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spacefx/link/Link.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from spacefx.common import Common_pb2 as spacefx_dot_common_dot_Common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17spacefx/link/Link.proto\x12\x38Microsoft.Azure.SpaceFx.MessageFormats.HostServices.Link\x1a\x1bspacefx/common/Common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x04\n\x0bLinkRequest\x12S\n\rrequestHeader\x18\x01 \x01(\x0b\x32<.Microsoft.Azure.SpaceFx.MessageFormats.Common.RequestHeader\x12`\n\x08linkType\x18\x02 \x01(\x0e\x32N.Microsoft.Azure.SpaceFx.MessageFormats.HostServices.Link.LinkRequest.LinkType\x12I\n\x08priority\x18\x03 \x01(\x0e\x32\x37.Microsoft.Azure.SpaceFx.MessageFormats.Common.Priority\x12\x10\n\x08\x66ileName\x18\x04 \x01(\t\x12\x14\n\x0csubdirectory\x18\x05 \x01(\t\x12\x18\n\x10\x64\x65stinationAppId\x18\x06 \x01(\t\x12\x11\n\toverwrite\x18\x07 \x01(\x08\x12\x17\n\x0fleaveSourceFile\x18\x08 \x01(\x08\x12\x32\n\x0e\x65xpirationTime\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"M\n\x08LinkType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06UPLINK\x10\x01\x12\r\n\tCROSSLINK\x10\x02\x12\x0b\n\x07\x41PP2APP\x10\x03\x12\x0c\n\x08\x44OWNLINK\x10\x04\"\x8c\x02\n\x0cLinkResponse\x12U\n\x0eresponseHeader\x18\x01 \x01(\x0b\x32=.Microsoft.Azure.SpaceFx.MessageFormats.Common.ResponseHeader\x12Z\n\x0blinkRequest\x18\x02 \x01(\x0b\x32\x45.Microsoft.Azure.SpaceFx.MessageFormats.HostServices.Link.LinkRequest\x12\x12\n\nfileSizeKB\x18\x03 \x01(\x03\x12\x35\n\x11linkProcessedTime\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampB;\xaa\x02\x38Microsoft.Azure.SpaceFx.MessageFormats.HostServices.Linkb\x06proto3')



_LINKREQUEST = DESCRIPTOR.message_types_by_name['LinkRequest']
_LINKRESPONSE = DESCRIPTOR.message_types_by_name['LinkResponse']
_LINKREQUEST_LINKTYPE = _LINKREQUEST.enum_types_by_name['LinkType']
LinkRequest = _reflection.GeneratedProtocolMessageType('LinkRequest', (_message.Message,), {
  'DESCRIPTOR' : _LINKREQUEST,
  '__module__' : 'spacefx.link.Link_pb2'
  # @@protoc_insertion_point(class_scope:Microsoft.Azure.SpaceFx.MessageFormats.HostServices.Link.LinkRequest)
  })
_sym_db.RegisterMessage(LinkRequest)

LinkResponse = _reflection.GeneratedProtocolMessageType('LinkResponse', (_message.Message,), {
  'DESCRIPTOR' : _LINKRESPONSE,
  '__module__' : 'spacefx.link.Link_pb2'
  # @@protoc_insertion_point(class_scope:Microsoft.Azure.SpaceFx.MessageFormats.HostServices.Link.LinkResponse)
  })
_sym_db.RegisterMessage(LinkResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\0028Microsoft.Azure.SpaceFx.MessageFormats.HostServices.Link'
  _LINKREQUEST._serialized_start=148
  _LINKREQUEST._serialized_end=660
  _LINKREQUEST_LINKTYPE._serialized_start=583
  _LINKREQUEST_LINKTYPE._serialized_end=660
  _LINKRESPONSE._serialized_start=663
  _LINKRESPONSE._serialized_end=931
# @@protoc_insertion_point(module_scope)
